///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesLogo = 'assets/images/logo.png';

  static const String svgBuildings = 'assets/svg/buildings.svg';

  static const String svgNoData = 'assets/svg/Oh no-amico 1.svg';
}
